robot_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - Rev1
    - Rev2
    - Rev3
    - Rev4
    - Rev30
    - Rev31
    - Rev32
  constraints:
          goal_time: 0.6
          stopped_velocity_tolerance: 0.05
          Rev1: {trajectory: 0.1, goal: 0.1}
          Rev2: {trajectory: 0.1, goal: 0.1}
          Rev3: {trajectory: 0.1, goal: 0.1}
          Rev4: {trajectory: 0.1, goal: 0.1}
          Rev30: {trajectory: 0.1, goal: 0.1}
          Rev31: {trajectory: 0.1, goal: 0.1}
          Rev32: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10